Revert "fixup! cqfd: style: use curve bracket when necessary"
This reverts commit e7aa285f76a7e6cd0ab086251b0de909eda3bca4.

FIXME:

	ERROR: invalid tag "cqfd_gportay_cqfd\\_test\\_5e6d5cf": invalid reference format